google_sheet_id = "1t0E6tuiqaj2QhQVvBzQOEL0A5uCq7PNuPNtcjDCop10"

[gcp_service_account]
type = "service_account"
project_id = "osrs-hard-clue-tracker"
private_key_id = "f3052c32cc77fbd374fa13ac0a9371a24abdf57f"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDZ77z6QLGvXFpa
3cLpxF5Ivl94WO8eAnQivLp6r2WcwRm8ONYzGsnZN+SySQDkrGBSKjG2Hg+oqxT8
rRmyGzIr62H6A4ebcgkHTHjXpAGmhOnUn5DnRG9zkOPAyh4rZ0F3xF+Hbxe04IJ4
6/072TCaaFrpPZMeDj8ENADzKpHyEnvjQkJ7jvZuMASwTpNXGjW+jXZooO/JoRHV
GB5EjeDoBtT7DrATv7pOD+GuVl2v2kQK+mYB0ywfk+kSiBUHJ7c01vL5KoX/yYFk
YztZ3H+fCt4XmePqncMFcdp4FnZme+7NSs8VPRAqjPOiNGUlkpGNJOxHoYj0TdE3
MYygj8SrAgMBAAECggEAHx/BVd4KYjhmwQZdsUP1kR77BHVzBM6l5lYcravB776W
Hc7iLF89h3OXiiyp336MrP9QpSkq5FQ2hZV1D34ZzrLphaqeYcFJ78xoj6dhAvaF
bHOzXovj/NWq6RwUbe9rpp6ZY/6mHJNZnspZGoR8j/iqTxgXnBm9vyxsHE4ulKry
h2IdvxGVkq5WZsYM8peUwaPTu0HN0UfI80cg+3jer+Bb3YeWZ0Bd+gcMq63O7NJ8
NQGC0KoDab1UeesO+s/hrn01Xcl4Qi4CLHjQj9xsoODCoSqZ68k+m6n27i+VFIg+
0HBuxUADLSlFPwQ1Jlli/rYIvz3FMa4eNUQ2JAvRCQKBgQD6tGbOkXtOZY18uxgF
ex0MmZpSG/Nu4POvEi8y8c/k+qmgbEz+PHOTRWiDAvQcjC5dYfy9dajh8y8hOwKy
BWwg3k1MkNMNqo0J2kuB8n0bLnZhshceJFRvtIdqvUFuIb38SF236gIAuXyzStIW
oUPjW5W2qX61uzfluQB4ScrU+QKBgQDeiidkSpexmYGxYRcbakXMPNNgR6hffwqf
P5Pchehqi5DvTkMcqw/j2MYKHlgopGRVgP8V6MULa9fpmdryPQyTjTsV715nCt9u
+pPfn43Ei8jWVN/jwVvKdqHNCWLtNuEcxdpOxS/OmWiyOgzlWOYeUep4XMq59wIz
xgGc312jwwKBgEjbwLzrnrAr5zCGlvaQzuJoiWavZNGmYmtQl5Lwn4BmMIHEt6Nz
Igt8smDQrOzW+Gp/HZpZ5Vi0+c9ofOILnV73+/Lya8Oe+xoP7L25IQ6TNCg0P2+t
EzTbfDdTBP7io3n79fCK+0YGoezhI6kb+MTMSvgozgA2hoomd7J9j4rRAoGASTTb
ZoOfST49StOsnUklct1jj52jBt8s6Fwq0PWAEmSdJgvxyeGAFaz+4N9AkwYZN4N6
5oMvJuWwHlmNi/iHRZbFJB8dR/psq/5kXMEJCuoNBGzhRfQatQy3h1KaJ3zRKvzv
JtB5PJZ8uXydN2k6MikyX6vuyKQ4Jj3x0+Aq1q8CgYEAo8GpdWCJ5Mn834UPNGaP
XbYmhNCg+d55hBDMlIG/3ostpEQO5FYxK2vjLEH24Zss5Yqi+7eXOkusLLzmFiIo
qJzQKhjd44S29pBrUuc9qZmtJIbjEgStHF4Th2kAOyscSKo30YVTD72z9eB9f80Z
Gr94GLMVN0SMLitZf2zz/AY=
-----END PRIVATE KEY-----"""
client_email = "osrs-hard-clue-tracker@osrs-hard-clue-tracker.iam.gserviceaccount.com"
client_id = "112481539473780328018"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/osrs-hard-clue-tracker%40osrs-hard-clue-tracker.iam.gserviceaccount.com"
universe_domain = "googleapis.com"